Repository karimmekdoud/Selenium_Automation_Framework_Team4, pull requests merged in 2020-06, with the labels that each got.

#1 First commit: ignore file/Driver are updated
  .gitignore
  Amazon/Amazon_Team_Test_Cases.txt
  Amazon/Extent-Report/ExtentReport.html
  Amazon/src/main/java/Home/Todaysdeals.java
  Amazon/src/test/java/testHome/TestHomePage.java
  Amazon/src/test/java/testHome/TestTodaysDeals.java
  Amazon/src/test/resources/AmazonTestRunner.xml
  Booking/Amazon_Team_Test_Cases.txt
  Booking/Extent-Report/ExtentReport.html
  Booking/src/test/java/testHome/TestHomePage.java
  Booking/src/test/java/testHome/TestLoginPage.java
  Booking/src/test/resources/BookingTestRunner.xml
  Empire/Amazon_Team_Test_Cases.txt
  Empire/src/test/resources/EmpireTestRunner.xml
  Geico/Amazon_Team_Test_Cases.txt
  Geico/src/test/resources/GeicoTestRunner.xml
  Netflix/Amazon_Team_Test_Cases.txt
  Netflix/src/test/resources/NetflixTestRunner.xml
  Sprint/Amazon_Team_Test_Cases.txt
  Sprint/src/test/resources/SprintTestRunner.xml
  TD_Bank/Amazon_Team_Test_Cases.txt
  TD_Bank/src/test/resources/TD_BankTestRunner.xml
  United_Airlines/Amazon_Team_Test_Cases.txt
  United_Airlines/src/test/resources/United_AirlinesTestRunner.xml
Labels: documentation

#4 Brahim ignore file updated
  .gitignore
  Amazon/Amazon_Team_Test_Cases.txt
  Amazon/Extent-Report/ExtentReport.html
  Booking/Amazon_Team_Test_Cases.txt
  Booking/src/test/java/testHome/TestHomePage.java
  Empire/Amazon_Team_Test_Cases.txt
  Geico/Amazon_Team_Test_Cases.txt
  Netflix/Amazon_Team_Test_Cases.txt
  Sprint/Amazon_Team_Test_Cases.txt
  TD_Bank/Amazon_Team_Test_Cases.txt
  United_Airlines/Amazon_Team_Test_Cases.txt
Labels: invalid

#2 ignorefile updated
  Amazon/Amazon_Team_Test_Cases.txt
  Amazon/Extent-Report/ExtentReport.html
  Booking/Extent-Report/ExtentReport.html
  Booking/src/test/java/testHome/TestHomePage.java
  Netflix/Extent-Report/ExtentReport.html
Labels: help wanted
